# Generated by Django 5.0.4 on 2025-11-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='recipient_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
