# Generated by Django 5.0.4 on 2025-11-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SareeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sarees/')),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.saree')),
            ],
        ),
    ]
